### ISSUE TITLE
Add Smokey feature for Manuals Publisher

### ISSUE THREAD

**Issue by floehopper** [alphagov/manuals-publisher#866]
At first glance, it doesn't look as if there are any features specific to manuals: https://github.com/alphagov/smokey/tree/master/features.

## Todo

- [x] Add manuals-publisher permissions to test signon user
- [x] Add test for manuals-publisher (alphagov/smokey#258)
- [x] Enable notifications for Smokey build failures (alphagov/govuk-puppet#5825)
- [ ] Check that we're receiving email notifications for Smokey build failures

**Comment by floehopper** [comment]
The only smoke tests for a publishing app are [these ones for the mainstream publisher](https://github.com/alphagov/smokey/blob/dcdb20630accdca0aa2216b38cfff83035b6b343/features/mainstream_publishing_tools.feature), but at least there is a precedent.

**Comment by danielroseman** [comment]
Sorry to barge in on your thread, but the publishing platform team are doing some work on running end-to-end tests from apps to frontends in CI using Docker, see https://github.com/alphagov/publishing-e2e-tests - might be useful for manuals-publisher too.

**Comment by floehopper** [comment]
@danielroseman: Thanks! That does sound very relevant.

**Comment by chrisroos** [comment]
We think that having some Smokey tests would have alerted us to the problem we started seeing after upgrading to Mongoid 3 in PR #929. We were seeing 504 Gateway timeout errors when viewing the /manuals index page.

**Comment by chrisroos** [comment]
Ruben in 2ndline has granted the manuals-publisher permission to the test signon user.

**Comment by chrisroos** [comment]
I've opened PR alphagov/smokey#258 to add a test for manuals-publisher.

**Comment by chrisroos** [comment]
I've opened PR alphagov/govuk-puppet#5825 to enable email notifications for Smokey build failures.

**Comment by chrisroos** [comment]
I've received email notifications for Smokey build failures so I'm happy that this is all done. Closing.
